--- #YAML:1.0
name:                Graph-ChuLiuEdmonds
version:             0.04
abstract:            Find minimum spanning trees in a directed graph.
license:             ~
author:              
    - Petr Pajas <pajas@matfyz.cz>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Graph:                         0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
